### ISSUE TITLE
" signs in the item title breaking JSON file.

### ISSUE THREAD

**Issue by HiddenMarty** [SirRandoo/itemlist#23]
![bug](https://github.com/user-attachments/assets/c8292bb8-5c1f-4800-ba7c-b1732bc7c7e3)

Hey, when in-game items have special characters like " it will break the JSON and thus break the build. I know how to fix that but random streamers might not notice that problem. So I would have 2 solutions.

1. The easy one is adding a note in documentation about that.
2. Complex one would be to write a script to escape these kind of JSON breaking characters and add it to the build pipeline.

I know it works in the game so they must be fixing the JSON, but again that's additional work u might not want to engage in for such edge cases.

F.Y.I. That's the error it created in the build pipeline.
` Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v232 GitHub Pages: jekyll v3.10.0 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-remote-theme Requiring: jekyll-feed Requiring: jekyll-paginate Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings Requiring: jekyll-remote-theme GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... Theme: sylhare/type-on-strap Theme source: /tmp/jekyll-remote-theme-20240911-9-o0kz6w Remote Theme: Using theme sylhare/type-on-strap Remote Theme: Downloading https://codeload.github.com/sylhare/type-on-strap/zip/HEAD to /tmp/jekyll-remote-theme-20240911-9-umv1om.zip Remote Theme: Unzipping /tmp/jekyll-remote-theme-20240911-9-umv1om.zip to /tmp/jekyll-remote-theme-20240911-9-o0kz6w Requiring: jekyll-feed Requiring: jekyll-paginate Requiring: jekyll-seo-tag EntryFilter: excluded /Gemfile.lock EntryFilter: excluded /Gemfile github-pages 232 | Error: (/github/workspace/_data/StoreItems.json): did not find expected ',' or '}' while parsing a flow mapping at line 7413 column 2 Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20240911-9-o0kz6w `

**Comment by SirRandoo** [comment]
Thank you for the suggestion! Its been a known issue with Twitch Toolkit for years, but as of 0bc82b1, the problem should be resolved with the new script.
